name: Nightly
on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '0 4 * * *'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn --frozen-lockfile --ignore-optional
      - run: yarn lint
      - run: yarn test
      - run: |
          yarn build
          ls -al dist
